package com.frame.hariko.mapper;

import com.frame.hariko.entity.Student;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated
     */
    int insertSelective(Student record);

    /**
     * 此方法返回满足条件的记录数;<br/>
     * 此返回条件判断其值不为 null且不为空'';<br/>
     * 若strict为true则精确匹配所有值,若为false则模糊匹配所有类型为String的值;<br/>
     * This method was generated by MyBatis Generator.<br/>
     * This method corresponds to the database table<br/> student
     *
     * @hariko.generated Thu Dec 20 14:57:54 CST 2018
     */
    Integer countByModelSelective(@Param("cond") Student cond, @Param("strict") boolean strict);

    /**
     * 此方法删除满足条件的记录数;<br/>
     * 此条件判断其值不为 null且不为空'';<br/>
     * 若strict为true则精确匹配所有值,若为false则模糊匹配所有类型为String的值;<br/>
     * This method was generated by MyBatis Generator.<br/>
     * This method corresponds to the database table<br/> student
     *
     * @hariko.generated Thu Dec 20 14:57:54 CST 2018
     */
    Integer deleteByModelSelective(@Param("cond") Student cond, @Param("strict") boolean strict);

    /**
     * 此方法根据cond设置条件更新model中设置的字段值;<br/>
     * 此条件判断其值不为 null且不为空'';<br/>
     * 若strict为true则精确匹配所有值,若为false则模糊匹配所有类型为String的值;<br/>
     * This method was generated by MyBatis Generator.<br/>
     * This method corresponds to the database table<br/> student
     *
     * @hariko.generated Thu Dec 20 14:57:54 CST 2018
     */
    Integer updateByModelSelective(@Param("cond") Student cond, @Param("strict") boolean strict, @Param("model") Student model);

    /**
     * 此方法返回满足条件的多条记录.<br/>
     * 此返回条件判断其值不为 null且不为空'';<br/>
     * 若strict为true则精确匹配所有值,若为false则模糊匹配所有类型为String的值;<br/>
     * 注意：java的Date不能完成匹配Oracle Date类型，即insert date into table 然后使用同一值date select是取不到对应记录的.<br/>
     * 
     * This method was generated by MyBatis Generator.<br/>
     * This method corresponds to the database table student
     *
     * @hariko.generated Thu Dec 20 14:57:54 CST 2018
     */
    List<Student> selectByModelSelective(@Param("cond") Student cond, @Param("strict") boolean strict);

    int insertBatchSelective(List<Student> records);

    /**
     * 此方法返回满足条件的单条记录.<br/>
     * 此返回条件判断其值不为 null且不为空'';<br/>
     * 若strict为true则精确匹配所有值,若为false则模糊匹配所有类型为String的值;<br/>
     * 注意：java的Date不能完成匹配Oracle Date类型，即insert date into table 然后使用同一值date select是取不到对应记录的.<br/>
     * 
     * This method was generated by MyBatis Generator.<br/>
     * This method corresponds to the database table student
     *
     * @hariko.generated Thu Dec 20 14:57:54 CST 2018
     */
    Student selectOneByModelSelective(@Param("cond") Student cond, @Param("strict") boolean strict);
}